### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Mayot**
synthax error in package name example

### CODE REVIEW

**Comment by phax** [comment]
@Mayot  thanks for pointing out a mistake.

However, if I build the commandline client (CLI) via Maven (`mvn clean install`) I get the file names `en16931-cii2ubl-cli-full.jar` - so the `x.y.z` part is incorrect and not the `full` part. 

Do you agree?

**Comment by Mayot** [comment]
Exactly, you're right, sorry for not going through the whole process of testing.

**Comment by phax** [comment]
No worries :)
Can you eventually just make the modifications in your branch, or shall I make it directly and close this PR?

**Comment by phax** [comment]
Pushed it myself. Thanks for pointing it out

**Pull request closed without merging**
